### ISSUE TITLE
Add travis CI

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#111]
@ojhall94 @nielsenmb   Shall we add travis CI to the repo?  We are now public so this should be easy to do.

**Comment by ojhall94** [comment]
We should for sure! Do we trust our unit tests?

**Comment by nielsenmb** [comment]
I'd say we should, I'd also like to find one that does documentation
coverage checking.

**Comment by grd349** [comment]
We need more tests for sure - and we need more comprehensive and perhaps slow tests but we need more tests.  

I have been playing with the @pytest.mark.slow decorator as suggested by @drstevenhale.  We could probably make use of this to build some end-to-end tests where we check the output mode frequencies.  

And yes @nielsenmb - checking doc coverage would be an idea.  We can also do this as part of the code review though.

**Comment by ojhall94** [comment]
Yeah great suggestion, I agree!

**Comment by nielsenmb** [comment]
Example travis CI configuration file. https://github.com/hannorein/rebound/blob/master/.travis.yml

Looks like you can do something with ipynb files too...

**Comment by grd349** [comment]
Yes - neat.

I think the import bit is this step ...

python ipynb2py.py AdvWHFast.ipynb

Defo worth looking into!

G
*Dr Guy R. Davies*
PI - ERC CartographY Project
Senior Lecturer in Astrophysics
School of Physics and Astronomy
The University of Birmingham
Edgbaston
Birmingham  B15 2TT

Tel +44 (0) 121 414 4597
G.R.Davies@bham.ac.uk
grd349@gmail.com
davies@bison.ph.bham.ac.u <davies@bison.ph.bham.ac.uk>k
<davies@bison.ph.bham.ac.uk>

The contents of this e-mail may be privileged and are confidential. It may
not be disclosed, used, or copied in any way by anyone other than the
addressee. If received in error please notify the sender then delete it
from your system. Should you communicate with the sender by e-mail, you
consent to The University of Birmingham monitoring and reading any such
correspondence.

**Comment by nielsenmb** [comment]
Travis CI seems to be working now.
