### ISSUE TITLE
New lightkurve functionality

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#126]
Lightkurve has new functionality - Oli knows more perhaps but this includes a stitch function among other things.  Shall we jump onboard and put everything we can into the examples?

I vote yes - it will be something todo for the TASC week.

**Comment by ojhall94** [comment]
Yeah! Instead of having to do all the appending by hand,

`lc = datalist.download_all().stitch()`

is a thing now!

**Comment by grd349** [comment]
Awesome! Let's add it!

**Comment by nielsenmb** [comment]
Hell yeah

**Comment by grd349** [comment]
OK - we have stitch in the docs examples.  We should add stitch under the hood too but later ...
