### ISSUE TITLE
Add K2 and TESS examples

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#127]
Mainly to see if we can.

@ojhall94 - can you suggest the two targets you have been looking at?  I'll see if anyone at TASC with a Lightkurve life membership can suggest the best way to treat the K2 systematics.

I can run these targets and then I'll ask ask for review.

**Comment by ojhall94** [comment]
You mean for my tutorial examples? TOI-197 for TESS and EPIC 201367296 for K2.

The notebooks are at www.github.com/ojhall94/TASC5_lightkurve :)

**Comment by grd349** [comment]
Cool - I'm wheels up in 20 so I'll look at those tomorrow! Good work.

**Comment by grd349** [comment]
Cool - I'm wheels up in 20 so I'll look at those tomorrow! Good work.

**Comment by grd349** [comment]
Done in the examples in docs.  We should do this under the hood too.

**Comment by grd349** [comment]
Done - Should we add words around the jam and then put in docs?

**Comment by nielsenmb** [comment]
Secondary priority, if the reader follows the main notebooks, they should
be able to follow the TESS notebook.

I'll add a note under User Guides that there are more useful examples under
in the GitHub examples directory.

**Comment by grd349** [comment]
Awesome - great.  Closing issue ...
