### ISSUE TITLE
Notes on docs

### ISSUE THREAD

**Issue by ojhall94** [grd349/PBjam#131]
I've gone through everything in readthedocs that isn't the API. These are my observations.

**Introduction**
- [x] We should change `pip install pbjam` to `pip install pbjam –user` 

**Session**
- [x] Since this is the quickstart guide, we should add a couple of comments into the first sell, specifically on the make_plots and path parameters explaining exactly what they do.

- [x] On that note, we should showcase what the output looks like, maybe by reading it in as a pandas dataframe and printing the head.

- [x] It would be neat if we added a little sentence or two about the star this notebook looks at with a hyperlink to the paper we take the numax, deltanu and teff from. Gives new users a foothold.

- [x] We should delete the empty bottom cell to make it a little tidier :) 

- [x] We should expand the acronym HMC to Hamiltonian Monte Carlo (HMC), as theres no hyperlink to an explanation.

All the hyperlinks work a-ok.

**Star**
- [x] In the first paragraph of ‘preparing the data’, the `lightkurve.periodogram` appears as a funky hyperlink that doesn’t go anywhere.

- [x] There is a cell, lc0.plot(), which should show the plot underneath it but doesn’t.

- [ ] We should
```python3
import warnings
warnings.filterwarnings(‘ignore’)
```
To avoid that annoying AstropyDepricationWarning popping up in our nice example.

- [x] We should add a note when using pg.flatten() that this is sub-optimal compared to a fit to the granulation background.

- [x] Pg.plot() should show a plot, ideally.

- [x] When calling pb.star, add a note that we’re not using the path parameter and that therefore our data will save in our working directory.

- [x] ‘The next step is to fit asymptotic’ should be ‘The next step is to fit an asyptotic’ or ‘The next step is to fit the asymptotic (with reference here)’

- [x] Still a citation needed for glitches.

- [x] When calling pb.peakbag, specify that star.f and star.s are the frequency and power of our periodogram.

- [x] Remove the last empty cell to make it look tidier :)

Hyperlinks work a-ok.

-	Advanced
- [x] We should turn off warnings

- [x] Top between cells 10 and 11, it’s should be its.

- [x] Between the first two equations in the asy_peakbag section theres a broken latex command.

- [ ] Earlier in the epsilon section, you say that we will explain what the epsilon parameter is later. In the asy_peakbag section where you note the asymptotic relation and explain the parameter epsilon, I would add a little line that says ‘…is commonly referred to as an offset, and is the parameter we calculated using the epsilon function above’ or something to that effect.

- [x] After the equation for mode height there is a broken latex command.

- [ ] Cell 28 has an error output at the moment

- [x] In the second paragraph of the peakbag section theres an ‘inn’ which should be ‘in’.

- [x] In the following paragraph theres a typo ‘develope’.

- [x] If we’re being pedantic (and why note), pymc3 should be PyMC3 in all instances.

- [x] There’s still a TODO in here!

- [x] Theres a typo ‘perfrect’

- [x] There’s a typo ‘differnet’

- [ ] I would add a dashed line at the 0 mark in cell 35, but looks like this section isn’t fully complete yet :)

**Help & Contact**
- [x] We should add my email to the Help & Contact.

**Comment by ojhall94** [comment]
Done with comments! As for the level of the content in the Advanced notebook (which looks sick, btw), we should give it to somebody with statistics skill but no involvement in this program to see if they can follow. Alex is a good shout, or perhaps Bill.

**Comment by nielsenmb** [comment]
Thanks for the comments Oli, I don't have power on my laptop (forgot adapter at airbnb)

I'll fix session and star tomorrow.

**Comment by grd349** [comment]
Bill had the following comments: 

- [ ] Front page:   Tweak first line to “… oscillation spectra of solar-like oscillators.”
- [ ] “… with much fewer priors in place” Than what?
- [ ] Straight-forward à straightforward (more than one instance) 
- [ ] Use guide: shown in the example below à shown in the examples below
- [ ] API: PBJam is can -> PBJam can

Bill also said:

> This is then confusing: “This allows for a more accurate model of the spectrum of frequencies, than the heavily parameterized models like the asymptotic relation.”, because the preceding paragraph says PBJam fits the asymptotic relation; I understand it’s the mode ID that is based on the asymptotic relation, not the actual bagging. Needs a tweak to the wording just to be clear (I had to re-read a couple of times before the difference hit home).

- [ ] Tweak wording to reflect this.

**Comment by grd349** [comment]
Great job everyone - I think we have done all we can here for now.  I'm closing and we can make new issues as problems occur.

Thanks everyone - sterling work!
