### ISSUE TITLE
should Inspector remain in this repo?

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#134]
In future it could be moved to the pbjam subdirectory and be polished to read pickled peakbag results. So it becomes a proper module in pbjam.

**Comment by grd349** [comment]
Good plan!

How long does it take to read in on of the pickled objects?  If it takes too long, shouldn't we stick to reading in the plots as these are quick?

**Comment by grd349** [comment]
We do need a little more effort on the inspectr.  Perhaps we should remove it and place it in a separate repo?

**Comment by nielsenmb** [comment]
Yes, I agree, but only temporary, I like it as a simple way to review the results, instead of having to set a .py or .ipynb etc.

**Comment by nielsenmb** [comment]
Move Inspectr to separate repo, but make it public.
