### ISSUE TITLE
Inspectr needs to be updated

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#137]
This is an issue that is not critical to the functionality of PBjam itself.

Inspectr is a module that is semi-separate from PBjam itself, and is meant as a visualization interface to inspect the results from PBjam on a star by star basis. 

It needs to be updated though, as it was developed initially during early days of PBjam.

Below is a list of idea for improving the Inspectr interface.

- [ ] Polish up the interface
- [ ] Flip between the plots from epsilon, asy_peakbag, peakbag etc.
- [ ] Optionally take the pickled star class instance as input
- [x] Point Inspectr at a directory and it'll loop through the fit solutions in that directory.
- [ ] Make it awesome.

**Comment by grd349** [comment]
Has this been done now @nielsenmb ?

**Comment by nielsenmb** [comment]
I'd say there's still room for improving inspectr, it still doesn't show the fit results in relation to the prior for example.

I guess for now this can be closed.

**Comment by grd349** [comment]
Clsoing
