### ISSUE TITLE
Automatic and robust large sep. and numax

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#138]
PBjam currently relies on accurate values of numax and the large separation. 

Ideally this should be measurable directly from the time series / power spectrum, in the event that previously measured values are not available. 

Initially this module should be a separate module from jar, asy_peakbag, etc. but if it proves reliable it may be integrated more directly in, e.g., the session class.

**Comment by grd349** [comment]
Yes - we can use Oli's work in lightkurve but we'll need to add uncertainties.  I have an idea.

**Comment by nielsenmb** [comment]
Me too!

**Comment by ojhall94** [comment]
Yessss use lightkurve for first guesses!

**Comment by nielsenmb** [comment]
But you told me yourself it doesn't always work!

I want <1% accuracy on 99.9% of targets!

We can/will enhance it though.

**Comment by ojhall94** [comment]
> But you told me yourself it doesn't always work! I want <1% accuracy on 99.9% of targets! We can/will enhance it though.

This sounds like a measurement, not a first guess 😛

But yeah we could totally improve or hack it to suit our needs better.

**Comment by nielsenmb** [comment]
This is is a problem description for the PBjam Hackday:

**Problem:** dnu and numax are two important input parameters in PBjam, however to a non-seismologist it may not be entirely clear how to measure these quantities or where to look them up. Furthermore we have found that PBjam is sensitive to bad estimates of dnu. The idea is to write a module that automatically and robustly measures either one or both of quantities to the precision that PBjam needs. 

**Requirements:** The method must provide accurate estimates of either dnu or numax, or both. It must work in the same way for all solar-like oscillators, without any switches to distinguish between, e.g., MS or RGB stars. It must work for low SNR cases and alert the user if no reliable estimates can be provided. It must require little to no user input is required so it can be integrated into the session class.

**Possible solution:** Use the prior information to restrict possible solutions. To estimate dnu alone, given an initial estimate of numax, one can use the prior to restrict a 1D ACF of the power spectrum to a small range in frequency lag. Furthermore, given the knowledge of the simple repeating pattern of the l=0 modes, a filter can be applied to the spectrum to smooth out the resulting ACF. The kernel can be a series of top-hats spaced at the estimated dnu (again based on the input numax). This makes the best dnu estimate easier to identify in low SNR cases and also reduces the effect of mixed modes that don't adhere to the regular spacing.  

To estimate both dnu and numax, perhaps the prior restriction may also be applied to the 2D ACF, which is often collapsed along either axis to estimate dnu and numax. However this method sums up a lot of power from parts of the ACF that only contribute noise to the collapsograms. This effect can be reduced by applying a mask to the 2D ACF that restricts the possible solutions to +/-5 sigma, say, of the prior sample that we already use in PBjam.
