### ISSUE TITLE
Epsilon is missing from API read the docs

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#140]
We could possible also add the new mcmc module.  

If you show me how to do this, I promise I will learn and not immediately forget.

**Comment by nielsenmb** [comment]
I didn't want to add epsilon cause I felt like it should be renamed to KDE
or something similar.

It's easy to add new content to the api page. Will take 5mins to show you

**Comment by grd349** [comment]
Yes - I was speaking with Christina Hedges and she had some ideas on how to improve the UI.  Right . now the names of our modules are a little bit obscure.  We might want to rename all of them :)

**Comment by grd349** [comment]
We should add it for now and then work on polishing up the UI.
