### ISSUE TITLE
KDE band width: automate

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#144]
We can get a modest speed up by using less stars in the KDE in epsilon.  

Simply selecting all stars that lie within X (suggest 10) sigma for dnu and numax will do this.  We should then dynamically determine the band width using the cross validated maximum likelihood method.

This will also help a little as the band width will be optimised for the local region rather than optimised on the whole sample.

**Comment by nielsenmb** [comment]
At the moment speed is irrelevant. Make it work, then optimize.

Anyway, sounds like it could work, but wouldn't it still be problematic in
sparse areas of the prior sample? If the errors on dnu and numax are set
too low.

**Comment by grd349** [comment]
> At the moment speed is irrelevant. Make it work, then optimize. 

So it's working well now and this is a suggestion for V2.0.  Things will slow down as we add more and more prior data.  It will be 16 times slower in epsilon when we add the Yu sample - uh oh :)

I would suggest a catch that takes a minimum of 100 stars for the KDE to prevent problems when people use uncertainties that are too small.

**Comment by nielsenmb** [comment]
True!

Yes that might work.

**Comment by nielsenmb** [comment]
Warrick did some profiling of the code though, and the lor function in
asy_peakbag was what ate up most of the time, calling the KDE from
statsmodels was a bit further down the list.

**Comment by grd349** [comment]
A rough guide for a red giant with 4 years of data is that epsilon sampling runs at around 60 it/s on my laptop.  The asy_peakbag runs at around 30 it/s on my laptop.  This means typically that epsilon runs in ~ 30 secs and asy_peakbag in ~ 1min (+ a bit because of harder convergence).  So the KDE overhead in asy_peakbag is about half the time.

If we put 16000 stars in the prior it will take ~ 8 mins to run epsilon and about 8.5 mins for asy_peakbag.  Then we need it! :)

**Comment by grd349** [comment]
This is done now in priors.kde()
