### ISSUE TITLE
Pass the epsilon object not the samples to asy_peakbag.

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#145]
Currently we pass the epsilon samples into asy_peak bag - this is crazy, we should pass the whole epsilon class.  This will allow us to use the instance of epsilon that is already there as the prior in asy_peakbag.  This is just much better style compared with making a new instance as we (well I did it so my bad) at the moment.

**Comment by nielsenmb** [comment]
Personally I would prefer to call epsilon inside asy_peakbag, or at least
leave it as an optional input. Makes it easier to use asy_peakbag.

**Comment by grd349** [comment]
The way we have it right now we make two instances of the epsilon class and this takes more memory than a single class.  Also, there is over head in reading in the prior data and constructing the KDE.  We don't really need to do this.  

There is also a possible speed up to be have from internally working `epsilon` to produce a multivariate description of the posterior to be used in asy_peakbag that would be much much faster than the KDE - especially when we have many more stars in the prior data.  

I think I'm quite keen on doing this :)

**Comment by nielsenmb** [comment]
>
> The way we have it right now we make two instances of the epsilon class
> and this takes more memory than a single class


This doesn't conflict with having epsilon called internally in asy_peakbag.

  internally working epsilon to produce a multivariate description of the
> posterior to be used in asy_peakbag


You'll have to explain this to me in more detail.

**Comment by grd349** [comment]
> You'll have to explain this to me in more detail.

We can well approximate the posterior from `epsilon` as a multivariate normal distribution with mean mu and covariance cov.  i.e.,

P(M | D) ~ Mv(mu, cov)

The assessment of the log likelihood function of a multivariate Gaussian is easy to do (propto X cov^(-1) X^T) and this would be must faster to evaluate than the KDE.  It could make asy_peakbag much faster.

Make sense?

**Comment by nielsenmb** [comment]
Sure, but how do you guarantee its Gaussian?

**Comment by grd349** [comment]
If we did the KDE correctly it will be! :)

Besides, the KDE is already an approximation - another one wont hurt.

**Comment by nielsenmb** [comment]
calling asymptotic_fit now at least requires a star class instance which hast he epsilon attributes (and thus the epsilon.samples), or optionally just the epsilon class instance
