### ISSUE TITLE
Examples: remove mydir for ./

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#148]
I keep running the examples and forgetting to change ./mydir to ./ and the code breaks because ./mydir does not exist.  We need to fix this ASAP.  It's a pain to run the code only to faile because the dir does not exist. 

Do we, 

1.  Change mydir to ./ in the examples.
2. Add directory creation if directory does not exist.
3. Both of the above.

I reckon 3. - thoughts from the team ...

**Comment by ojhall94** [comment]
3! Directory creation is always safest imo

**Comment by nielsenmb** [comment]
Sure, we can do that.

The notebooks in docs where never meant to be run though. Since they are
the ones that are show on readthedocs. They're meant to be read-only, so
that they don't disappear if there's a typo in the ipynb.

The ones you can play around with are in the Examples directory.

**Comment by grd349** [comment]
Good point - I didn't think about that.

We need to add text to the Examples :(

We should also do this fix anyway.  Perhaps people will follow the example by typing the instructions them selves.  It would still be annoying for it to fail.

**Comment by nielsenmb** [comment]
I think if the user is typing out those examples they should know that they don't have a directory called mydir. It's like the stackoverflow examples, dir=/dir/where/code/is etc. it's pretty obvious that line needs to be changed.
