### ISSUE TITLE
Add warning when input star not like prior stars

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#150]
PBjam is unlikely to work (it will probably crash) when the input star is very different to the stars in the prior data.  As we sill out the prior this will become less of an issue.  In the mean time we should add a warning that input is very different from prior and results may be wild.

One test might be to see if the KDE prior returns a finite number - the other might be to use a distance metric and set a threshold somehow.  This will need a little thought.

One very quick starting point maybe to warn about any stars with numax > 250 muHz.

**Comment by nielsenmb** [comment]
For now I think the numax warning is most meaningful/relatable for users.

**Comment by grd349** [comment]
There is now a warning about the number of stars in the prior.
