### ISSUE TITLE
Pytest tests should import locally instead of the installed package

### ISSUE THREAD

**Issue by ojhall94** [grd349/PBjam#151]
At the moment, the preamble to the tests include:

`import pbjam`

This imports whatever version is installed on the users machine instead of testing the latest changes to the code. Instead we should do something like:

`from ..jar import session`

to perform tests on session specifically, for example.

**Comment by grd349** [comment]
Yes - excellent spot.  I'll look at fixing this when back unless someone else can in the mean time.

**Comment by nielsenmb** [comment]
if I do
`from ..asypeakbag import asymptotic_fit`

in pbjam/tests/test_asy_peakbag.py

I get 

> ValueError: attempted relative import beyond top-level package

**Comment by nielsenmb** [comment]
I think this has been done for a while now.
