### ISSUE TITLE
seems safe to remove astropy version requirement

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#172]

**Comment by warrickball** [comment]
`lightkurve` is also now up to version 1.3.0, which I presume is still compatible with PBjam, so that's also giving me `pip` warnings. Really, you (we?) should use `>=` for required versions whenever possible.

**Comment by grd349** [comment]
Good point - but we haven't tested lk 1.3.0 with PBjam.  But you are right - we should switch to >= for versions and then deal with new version issues as they are reported (lk does not seem to be soo hot on maintaining backwards compatibility).

**Comment by nielsenmb** [comment]
Yup. Definitely worth keeping in mind about the version exclusion!
