### ISSUE TITLE
Session: LightCurve objects store differently in numpy arrays / pandas for lightkurve>=1.2

### ISSUE THREAD

**Issue by alexlyttle** [grd349/PBjam#176]
This relates to an [issue I raised](https://github.com/KeplerGO/lightkurve/issues/619#issue-515612455)  on the Lightkurve GitHub page.

The impact of this issue is in `session.py`, particularly upon initialisation of `session` when importing  timeseries. In my case, I provided paths to the timeseries files. When I try to initialise `session`, 

```python
sess = pb.session(dictlike='data/targets/target_data_with_lc_path.csv')
```

the code hangs on the final line ([399 in session.py](https://github.com/grd349/PBjam/blob/1c43c7ffc475c2d4ee5f2ed51b0b8ce0f49c796b/pbjam/session.py#L399)) of the following block of code:

```python
key = 'timeseries'
for i, id in enumerate(vardf['ID']):
    if isinstance(vardf.loc[i, key], str):
        t, d = np.genfromtxt(vardf.loc[i, key], usecols=(0, 1)).T
        d += tinyoffset
        vardf.loc[i, key] = arr_to_lk(t, d, vardf.loc[i, 'ID'], key)
    ...
```

The variable `vardf` is a dictionary containing star data and the path to timeseries file. Pandas tries to convert the LightCurve to a numpy array. Before Lightkurve 1.2, this works fine. However, changes to lk mean that from 1.2 onward, the LightCurve object explodes into objects for each value of time/flux when converted to a numpy array. Naturally, this takes a very long time and would result in an error as it is one dimension too large.

I suggest we change the requirements of PBjam to not include lightkurve 1.2 and 1.3? Unless someone can offer an alternative to the above code (and elsewhere) which stops the LightCurve object exploding?

I will update with any response to the lightkurve issue.

**Comment by grd349** [comment]
Hi @alexlyttle,  Did you hear back from the lightkurve folks?

**Comment by alexlyttle** [comment]
They replied [here](https://github.com/KeplerGO/lightkurve/issues/619#issuecomment-548589539). The simple fix suggested, translated to this issue, is to write:

```python
obj = np.empty(1, dtype=object)
obj[0] = arr_to_lk(t, d, vardf.loc[i, 'ID'], key)
vardf.loc[i, key] = obj
```

(There may be a more simple way of doing this with pandas alone, I am not sure)

I reckon a simple fix would be to implement this in places in the code where a Lightcurve object is added to a pandas DataFrame or numpy array. It's a little ugly but if it works then it will do!

**Comment by alexlyttle** [comment]
I should update. This may be closed now. @nielsenmb's change from using pandas `DataFrame.loc[]` to using `DataFrame.at[]` has fixed this issue as a side-effect. I believe `DataFrame.at[]` targets a specific cell and will put the `LightCurve` object into it, whereas the former would explode the `LightCurve` by using it's `__len__` method.

**Comment by grd349** [comment]
Super - thanks @alexlyttle.  Great job!
