### ISSUE TITLE
readthedocs no longer compiling due to missing nbsphinx

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#178]
Apparently readthedocs can't figure out the extra_require variable in setupy.py and is not install nbsphinx causing the compilation of the docs to fail.

**Comment by grd349** [comment]
How do we fix this?

**Comment by nielsenmb** [comment]
For now by removing nbsphinx from the  extras_require in setup.py, and
putting it back in requirements.txt.

There is probably a better way to do it, probably by fiddling with the
docs/conf.py file, but I don't know for sure.

**Comment by nielsenmb** [comment]
temporarily fixed
