### ISSUE TITLE
incorrect mode identification for main sequence stars

### ISSUE THREAD

**Issue by darthoctopus** [grd349/PBjam#180]
I'm trying pbjam with a main sequence star (16 Cyg A; KIC 12069424), using a power spectrum from the KASOC time series, and with stellar parameters instantiated as follows:

```
star = pb.star(kic, pg, 
               [2200, 50], [150,50], teff=[5830, 11], bp_rp=[0.8201175, 0.1])
```

calling `star()` returns the following l = 0,2 mode identifications:
![asymptotic_fit_12069424](https://user-images.githubusercontent.com/5761408/68613116-0d1a9580-048c-11ea-8d17-30caf0962341.png)

The l=1 ridge is being misidentified as l=0,2 modes, with a value of the small separation that is likely determined by noise peaks (2 μHz rather than ~8 μHz).

**Comment by nielsenmb** [comment]
Hi Joel, thanks trying this out. The main-sequence part of the prior is still a bit sparse. 

Can you try increasing the error on your Teff, \pm11 K is very small. I don't know if that'll affect anything, but we do have a Gaussian prior on Teff on top of the KDE, so if it's too narrow it might try to put epsilon at a wrong value. 

Also, when I was populating working on the main-sequence targets I found that increasing the bandwidth (to 2-4) of the KDE sometimes helped. This is the bw_fac optional parameter when you call session or star (after initializing it).

**Comment by grd349** [comment]
Hey @darthoctopus ,

Thanks for looking at this.  I'm trying to recreate this but Lightkurve doesn't like 16 Cyg (complains about multiple targets).  I guess you are using a custom lightcurve.  If you share the light curve (or even your notebook) I'll have a go.

First out the gate as a suspect here is your starting Dnu.  PBjam is really designed to work only if you give a decent estimate of Dnu (& Numax) to the code.  I think the results you are seeing are simply a manifestation of your large uncertainty in Dnu.  Could you retry with dnu=[103.4, 1.0]? 

Ta,

**Comment by darthoctopus** [comment]
Thanks @nielsenmb and @grd349 for the suggestions. As @grd349 suspects, pbjam is able to identify the modes correctly with a more constrained value of Δν.
