### ISSUE TITLE
kde 

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#181]
I ran ...

> PBjam version == 0.1.7

> %%time
> ep = pb.kde(verbose=True)
> result = ep(dnu=dnu, numax=numax, teff=teff, bp_rp=bp_rp)
> ep.plot(pg);

and got the following message:

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-17-4d5b9451edd5> in <module>()
> ----> 1 ep.plot(pg);

> AttributeError: 'kde' object has no attribute 'plot'

If this has really changed so the kde no longer has a plot method then we need to update the examples to reflect this.

@nielsenmb Is this part of your new plotting revamp.  Can we add a method to kde called plot that calls your new fancy plotting?

**Comment by nielsenmb** [comment]
plot() is ambiguous, so it's plot_spectrum() now. I updated the example-star.ipynb, but apparently not the advanced one.

**Comment by nielsenmb** [comment]
Also this is the least informative issue title ever
