### ISSUE TITLE
Inconsistent results between KDE prior and actual spectrum

### ISSUE THREAD

**Issue by darthoctopus** [grd349/PBjam#184]
I used the prior values (in the data file `reference_epsilon_values_do_not_change_this.csv`) for KIC 11717120 to attempt to identify modes and peakbag the [KASOC short-cadence power spectrum](https://github.com/grd349/PBjam/files/3841998/kplr011717120_kasoc-psd_slc_v1.zip). The relevant line from the CSV file follows:

```
11717120,4981.5,69.276,37.552,1.416,592.469,11.729,1.0478573,1.414,0.035,1.414
```

I created the star object as:

```
star = pb.star(kic, pg, [592.469, 11.729], [37.552,1.416], teff=[4981.5, 69.276], bp_rp=[1.0478573, 0.1])
```

This fails quite spectacularly:

![asymptotic_fit_11717120_original](https://user-images.githubusercontent.com/5761408/68778435-2db82c00-0601-11ea-97ef-5823f3359cdc.png)

**Comment by grd349** [comment]
Hi @darthoctopus 

Thanks for pointing this one out.  I think there are two things at play here that make this difficult.  First is that it looks like the prior is still a little bit on the sparse side in this region.  Second, the data SNR is really high (which is a good thing) but the modes are very narrow.

The code is finding a solution where is the mode line width is much higher than it should be.  In fact is very much in tension with the prior, it's just that the data are so good that the prior is overwhelmed.  This is sort of desired behaviour except the solution is the wrong one. 

Suggested fix - beef up the prior in only the line width parameter.  We need a penalty for the specific case that the line width becomes much larger than expected.  I'll have a think about what distribution that should be.

**Comment by grd349** [comment]
I hacked together a simple additional penalty on the line width and things behave much better.  My hack now forces a slight over estimate of the line width but at least I think I know what I'm working with here.

<img width="1037" alt="Screenshot 2019-11-14 at 04 43 18" src="https://user-images.githubusercontent.com/14784265/68827284-51c74c00-0699-11ea-9a52-1c24ea9a73ea.png">

**Comment by grd349** [comment]
OK - this works better now.  I'll make a PR for the changes.  They might still need a little more thought.

<img width="982" alt="Screenshot 2019-11-14 at 05 26 46" src="https://user-images.githubusercontent.com/14784265/68829012-66a6de00-069f-11ea-89f5-265352608d9a.png">

**Comment by grd349** [comment]
I have merged in the changes to the treatment of an additional linewidth penalty. @darthoctopus I think this will fix your particular problem and I hope this will more generally fix this issue of bad solutions from the data overwhelming the prior.  Please shout if you continue to have problems and thank you for the input!
