### ISSUE TITLE
Add example using own data sets

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#205]
@ojhall94 has a nice example of analysing 16 Cyg A where he uses his own data that he plus into lightcurve and then run PBjam `star`.  We should add this example to the docs somewhere.  

It's probably more about interacting with lightkurve than anything else but probably an issue users will care about.

We should add a few more orders to the example and we should fix the problem #204 to make it look nicer.

**Comment by nielsenmb** [comment]
Is there a link to this notebook? It sounds like that's what happens when you give pbjam.session a numpy array or file name instead of a lightkurve object. 

This is of course not possible if we want the tutorial to show the pbjam.star case, but for pbjam.session it's trivial.

**Comment by grd349** [comment]
@ojhall94 - do you have the 16 Cyg notebook?  We'll make it pretty if you can shoot it across.
