### ISSUE TITLE
Install problem w/ hdbscan

### ISSUE THREAD

**Issue by grd349** [grd349/PBjam#209]
When installing pbjam with pip3 I get a problem with hdbscan - failed building wheel for hdbscan.

> 
>  Failed building wheel for hdbscan
>   Running setup.py clean for hdbscan
> Failed to build hdbscan
> Installing collected packages: numpy, emcee, imagesize, six, pyparsing, packaging, sphinxcontrib-htmlhelp, sphinxcontrib-applehelp, sphinxcontrib-qthelp, sphinxcontrib-serializinghtml, sphinxcontrib-jsmath, certifi, idna, chardet, urllib3, requests, pytz, babel, snowballstemmer, alabaster, setuptools, Pygments, sphinxcontrib-devhelp, docutils, MarkupSafe, jinja2, sphinx, ipython-genutils, decorator, traitlets, entrypoints, pandocfilters, webencodings, bleach, jupyter-core, mistune, attrs, pyrsistent, more-itertools, zipp, importlib-metadata, jsonschema, nbformat, defusedxml, testpath, nbconvert, nbsphinx, python-dateutil, pandas, scipy, theano, patsy, h5py, tqdm, xarray, cftime, netcdf4, cycler, kiwisolver, matplotlib, arviz, pymc3, cython, joblib, scikit-learn, hdbscan, astropy, statsmodels, uncertainties, future, autograd, oktopus, soupsieve, beautifulsoup4, bs4, pycparser, cffi, cryptography, jeepney, secretstorage, keyring, html5lib, astroquery, fbpca, lightkurve, sklearn, corner, pbjam
>   Running setup.py install for hdbscan ... error
>     Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vg7xi9c1/hdbscan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1tmcdv31-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/prediction.py -> build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/hdbscan_.py -> build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/robust_single_linkage_.py -> build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/validity.py -> build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/__init__.py -> build/lib.linux-x86_64-3.6/hdbscan
>     copying hdbscan/plots.py -> build/lib.linux-x86_64-3.6/hdbscan
>     creating build/lib.linux-x86_64-3.6/hdbscan/tests
>     copying hdbscan/tests/test_rsl.py -> build/lib.linux-x86_64-3.6/hdbscan/tests
>     copying hdbscan/tests/test_hdbscan.py -> build/lib.linux-x86_64-3.6/hdbscan/tests
>     copying hdbscan/tests/__init__.py -> build/lib.linux-x86_64-3.6/hdbscan/tests
>     running build_ext
>     cythoning hdbscan/_hdbscan_tree.pyx to hdbscan/_hdbscan_tree.c
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-vg7xi9c1/hdbscan/setup.py", line 96, in <module>
>         setup(**configuration)
>       File "/home/davies/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/home/davies/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
>         self.run_command('build')
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/tmp/pip-build-vg7xi9c1/hdbscan/setup.py", line 26, in run
>         build_ext.run(self)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>         _build_ext.build_ext.run(self)
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
>         ext.sources = self.cython_sources(ext.sources, ext)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 347, in cython_sources
>         full_module_name=module_name)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 778, in compile
>         return compile_single(source, options, full_module_name)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 727, in compile_single
>         return run_pipeline(source, options, full_module_name)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 479, in run_pipeline
>         context = options.create_context()
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 597, in create_context
>         self.cplus, self.language_level, options=self)
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/Main.py", line 80, in __init__
>         from . import Builtin, CythonScope
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/CythonScope.py", line 5, in <module>
>         from .UtilityCode import CythonUtilityCode
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/UtilityCode.py", line 3, in <module>
>         from .TreeFragment import parse_from_strings, StringParseContext
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/TreeFragment.py", line 17, in <module>
>         from .Visitor import VisitorTransform
>       File "Cython/Compiler/Visitor.py", line 17, in init Cython.Compiler.Visitor
>       File "/home/davies/.local/lib/python3.6/site-packages/Cython/Compiler/ExprNodes.py", line 46, in <module>
>         from .Pythran import (to_pythran, is_pythran_supported_type, is_pythran_supported_operation_type,
>     ImportError: cannot import name 'pythran_is_numpy_func_supported'
>     
>     ----------------------------------------
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vg7xi9c1/hdbscan/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1tmcdv31-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-vg7xi9c1/hdbscan/

We should see if we can remove hdbscan for now so at least the basic functionality works.

**Comment by warrickball** [comment]
Is this still an issue? I just created a fresh virtual environment and `pip3 install pbjam` finished without an error. FWIW, I'm on Python 3.7.5 on Fedora 31.

If you keep having trouble, it might by a Cython issue so try upgrading it manually (e.g. `pip3 install --upgrade cython`).

**Comment by nielsenmb** [comment]
Apparently only Guy had this issue. It worked on multiple different
machines around the time of the PLATO meeting, so we thought it was an
issue that cropped up recently with a new version of HDBscan but apparently
not(?).

**Comment by alexlyttle** [comment]
I got this issue recently on BlueBEAR and realised it has something to do with not having a GCC compiler installed or in the PATH. I solved it by loading the compatible GCC module. In the process, I found some solutions, including the following thread [here](https://github.com/scikit-learn-contrib/hdbscan/issues/293) which suggested the command `sudo apt-get install python3.X-dev` where `X` is the version which matches your python installation. It can also happen after updating to macOS Catalina. However, on macOS it's a little different. I think it involves updating Command Line Tools for Xcode.

**Comment by grd349** [comment]
Super - thanks Alex. Do we think we can close this issue?

**Comment by alexlyttle** [comment]
I think it can be closed now, no need to make changes to PBjam to fix this. Although I realise your error is a little different from the one in the link I shared, it appears updating or uninstalling and reinstalling cython fixes your issue ([here](https://github.com/cython/cython/issues/2680)).
