### ISSUE TITLE
AttributeError: module 'pymc3' has no attribute 'diagnostics'

### ISSUE THREAD

**Issue by darthoctopus** [grd349/PBjam#210]
I get this error when trying to peakbag 16 Cyg (again); this is a regression from the last time I tried it in November. Traceback follows:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/Git/PBjam/pbjam/star.py in __call__(self, bw_fac, norders, model_type, tune, verbose, make_plots, store_chains, nthreads)
    281                              store_chains=store_chains)
    282 
--> 283         self.run_peakbag(model_type=model_type, tune=tune, nthreads=nthreads,
    284                          make_plots=make_plots, store_chains=store_chains)

~/Git/PBjam/pbjam/star.py in run_peakbag(self, model_type, tune, nthreads, make_plots, store_chains)
    235 
    236         # Call
--> 237         self.peakbag(model_type=model_type, tune=tune, nthreads=nthreads)
    238 
    239         # Store

~/Git/PBjam/pbjam/peakbag.py in __call__(self, model_type, tune, nthreads, maxiter, advi)
    357                                              target_accept=self.target_accept,
    358                                              progressbar=False)
--> 359                 Rhat_max = np.max([v.max() for k, v in pm.diagnostics.gelman_rubin(self.samples).items()])
    360                 niter += 1
    361 

AttributeError: module 'pymc3' has no attribute 'diagnostics'
```

I am using the current git master of pbjam (installed in develop mode) with pymc3 version 3.8.

**Comment by darthoctopus** [comment]
As far as I can tell, this is the result of an API change in pymc3 where native diagnostic functions were replaced in favour of using ArviZ: see https://github.com/pymc-devs/pymc3/commit/521174cfb52a4dfe7b8bd28b1ce193df58e9dd40

**Comment by grd349** [comment]
Hi @darthoctopus 

Good catch - I think you've got the problem understood.  @nielsenmb - we should fix this sap.

It might function better int he future if we take the diagnostics from the pm.summary(trace) functionality that way we'll be less prone to changes under the hood.  Thoughts?

**Comment by darthoctopus** [comment]
sorry to bother you all (this nagging is second-order), but any progress on this? Alternatively, as a workaround I'd like to downgrade pymc3 to whatever version you people are presently using/testing with. Any suggestions?

**Comment by nielsenmb** [comment]
Hi Joel,

I'm currently using pymc3 3.7 and pbjam works for me with this version. Not
sure what the others are using.

I haven't had much time to work on pbjam the last month, and might not for
a while (need to write that paper!).

**Comment by nielsenmb** [comment]
This should be fixed in the an upcoming PR once Guy approves it. 

It's preferable to update to 3.8, but it should still work for 3.7.

**Comment by nielsenmb** [comment]
Think this issue can be closed now.
