### ISSUE TITLE
kde.plot_spectrum() xlim is inconsistent

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#214]
It should be focused around numax, but appears to sometimes just take the full frequency range.

**Comment by nielsenmb** [comment]
This is being fixed in a PR I'm working on.

I relation to this, need some opinions on the corner plot of the stage result in relation to prior:
At start:
![star_corner](https://user-images.githubusercontent.com/18048879/75800642-cf5eb700-5d71-11ea-8fa5-f344f785e750.png)

After KDE:
![star_kde](https://user-images.githubusercontent.com/18048879/75800586-b524d900-5d71-11ea-89c6-607150d01905.png)

After Asy_peakbag:
![star_asy_fit](https://user-images.githubusercontent.com/18048879/75800667-d8e81f00-5d71-11ea-9ce4-e3895d60c71c.png)

**Comment by grd349** [comment]
Hi Martin,

Could you explain a little more.  For the data, why is the numax so bimodal?  How are you generating the black data - is it all the points from the prior or is it the output of the KDE (if it is the output of the KDE then something is not working)?

**Comment by nielsenmb** [comment]
Black is the prior, red is the latest stage values for the relevant parameters, so if it's called from the star class it plots the input values on top of the prior, if it's called from the KDE class it plots the KDE results etc. (doesn't work for peakbag of course). 

This star has numax at 312muHz (it's Eps Ret, a TESS target), putting it just beyond the Kepler long cadence Nyquist.
