### ISSUE TITLE
reggae UI issues

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#222]
List of issues for the reggae UI:

- [x] Should focus on the relevant area around numax (just pick min(nu_l0) to max(nu_l0) + a bit either side)
- [x] Dnu, epsilon, d02 can be fixed based on asy_peakbag output? i.e. they don't need to be in the list of sliders?
- [ ] Parameter values near for each slider
- [x] tight_layoout()
- [x] yscale seems to be fixed? Should be variable depending on star
- [x] y axis units should be SNR
- [x] Save directory should be the directory for the star, not the current path
- [x] Output filename should be prefixed with star name (see asy_peakbag, peakbag naming convention)
- [x] Save should print in lower left which directory is being dumped to
- [x] Should be awesome

**Comment by grd349** [comment]
I'll work on this.  I'm not going to make it too tidy as this is transient code but it could be improved for sure!

**Comment by grd349** [comment]
@nielsenmb 

What does 'Parameter values near for each slider' mean?

**Comment by nielsenmb** [comment]
Sorry, English malfunctioned when I wrote that sentence.

What I meant was what value the button on the slider is currently at. Just
to show that you're not changing dnu, say, to something completely
unreasonable.

**Comment by grd349** [comment]
:) Understood.  I'll look to see if I can do this easily.

**Comment by grd349** [comment]
Values on sliders - It is not easy and is a luxury feature.  I'm going to close this issue and point everyone to the cpnest PR that will fix all these things except values on sliders.

**Comment by nielsenmb** [comment]
Sure, no problem with me.
