### ISSUE TITLE
TS flattening should be based on input numax

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#225]
In session.clean_lc() the light curve is flattened. This is currently using the default setting which I think is 401 cadences (regardless of long or short cadence).

This might have adverse effects for stars with numax at a comparable frequency (period). 

The number of cadences to flatten with should be based on the input numax with a ceiling of some value (401?).

**Comment by grd349** [comment]
Agreed!  We should set the smoothing to be something like t_smooth = x / (numax) where numax is in Hz and x is some number greater than 10.  I think that makes sense. If numax is very very uncertain we should raise a warning.

**Comment by grd349** [comment]
Yes - we came across this agin the other day.  @nielsenmb we need a plan on this.  Shall we look at it tomorrow in WorkingWithYou?

**Comment by nielsenmb** [comment]
Sure

**Comment by nielsenmb** [comment]
No longer relevant with PR #276
