### ISSUE TITLE
plot_prior should plot the prior not the sample

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#227]
Currently the plot_prior function plots the latest stage result in relation to the prior sample.

It should probably plot the prior instead of the sample as this is a better diagnostic in case of bad fits.

**Comment by grd349** [comment]
In this context what is the prior and what is the sample.  Do we mean the samples drawn from the posterior in the first stage that then become the prior for asy_peakbag?

**Comment by grd349** [comment]
Bump @nielsenmb

**Comment by nielsenmb** [comment]
No longer relevant with PR #276
