### ISSUE TITLE
CPnest default settings need to be changed

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#254]
At the moment the maxmcmc and Nlive points values are probably too small for a high dimensional parameter space that we are using it for in asy_peakbag. 

@alexelthomas did some testing and found that for high dimensions (~10), and low maxmcmc (~100) produced a normally distributed marginalized posterior for parameters that had uniform priors and likelihoods. The reason for this is most likely because the walkers that CPnest uses in the sampling process are started in a tight ball, and a low maxmcmc doesn't allow them to explore the parameter space sufficiently. 

Chris suggested that parallelization should work for CPnest despite it not being beneficial for EMCEE. Also, apparently Dynesty is the new hot nested sampler in Grav Waves and better maintained compared to CPnest.

**Comment by alexelthomas** [comment]
Chris also suggested a minimum of 1000 live points and probably more like 2000
