### ISSUE TITLE
Cannot install PBjam in a clean Python environment

### ISSUE THREAD

**Issue by alexlyttle** [grd349/PBjam#256]
When installing a clone of the PBjam repo in a clean python environment it fails. This is because cpnest requires numpy in the setup process but numpy has not been installed. I think this may be a cpnest issue but I wonder if there is a way of forcing setup.py to install numpy before cpnest? Note: A manual fix is to just run `pip install numpy` before `pip install pbjam` but this may explain Travis CI build failures?

Here is the shell output

```bash
$ cd path/to/PBjam
$ pip install -e .

Obtaining file:///Users/ajl573/Repos/alexlyttle/PBjam
Collecting astropy>=3.2.1
  Using cached astropy-4.2-cp38-cp38-macosx_10_9_x86_64.whl (6.5 MB)
Collecting cpnest>=0.9.9
  Downloading cpnest-0.11.0.tar.gz (90 kB)
     |████████████████████████████████| 90 kB 3.9 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/ajl573/.virtualenvs/pbjam/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zr/3f9t9zzs1tq27438cp0fqn19z0ds79/T/pip-install-8hlndala/cpnest_ed009095d57b467e9d1299f0cfd6cf8e/setup.py'"'"'; __file__='"'"'/private/var/folders/zr/3f9t9zzs1tq27438cp0fqn19z0ds79/T/pip-install-8hlndala/cpnest_ed009095d57b467e9d1299f0cfd6cf8e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/zr/3f9t9zzs1tq27438cp0fqn19z0ds79/T/pip-pip-egg-info-r7el8bc1
         cwd: /private/var/folders/zr/3f9t9zzs1tq27438cp0fqn19z0ds79/T/pip-install-8hlndala/cpnest_ed009095d57b467e9d1299f0cfd6cf8e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zr/3f9t9zzs1tq27438cp0fqn19z0ds79/T/pip-install-8hlndala/cpnest_ed009095d57b467e9d1299f0cfd6cf8e/setup.py", line 3, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by nielsenmb** [comment]
Hmm...installing cpnest should install numpy if cpnest depends on it no?

Also, numpy appears first in the requirements.txt file, so if anything it would presumably start with numpy and work it's way through?

The Travis CI build fails were due to a version issue between Scikit-learn and the Mac OS that was being used in the Travis environment, and happened when running PyTest. The package installation works out fine.

I'll try to make a clean install. See what happens.

**Comment by alexlyttle** [comment]
The problem is cpnest imports numpy in its `setup.py` before it installs any requirements.

**Comment by alexlyttle** [comment]
I don't think that the order in `requirements.txt` matters, I think it ends up being sorted in alphabetical order by pip but I may be wrong.

**Comment by nielsenmb** [comment]
Sounds like a cpnest issue then.

How is it possible to install cpnest then at all if it doesn't install it's requirements first.

**Comment by alexlyttle** [comment]
cpnest uses numpy in the setup process, the script that is run when you do `pip install cpnest` or `python -m setup.py`. Typically setup.py files only import base-python libraries like `os` and `setuptools`. Setuptools is what handles installing the requirements and setup.py is the script that handles the whole setup process. They use numpy in their setup process and it is a fair assumption that all users will have numpy but it isn't great practice as packages should be able to install on a clean python build. Does that make sense?

**Comment by nielsenmb** [comment]
ah I assumed it was standard practice to not use any dependencies except base python stuff. 

The Travis CI build that I started for PR #255 worked fine though. 

It does pip install -r requirments.txt though, I donno if that behaves differently than setupy.py install

**Comment by nielsenmb** [comment]
This issue has been resolved by cpnest update.
