### ISSUE TITLE
manual override for ε prior?

### ISSUE THREAD

**Issue by darthoctopus** [grd349/PBjam#264]
In some cases, the prior placed on ε during the asymptotic fitting procedure is exactly out of phase with the true locations of the radial/quadrupole-mode ridges; however, the presence of the dipole mixed-mode forest permits a "good enough" fit to nonetheless be obtained (see attached figure: [echelle.pdf](https://github.com/grd349/PBjam/files/7489874/echelle.pdf)). In such cases, it is often possible to demand (by eye) a small range of values for $\epsilon_0$ in the asymptotic fit, with probably better accuracy than the KDE provides. Perhaps a manual override of the ε range should be permitted?

**Comment by nielsenmb** [comment]
I think we did have epsilon as an optional input initially, so I don't
think it'd be an issue to put it back in. It might also be a sensible thing
to do when it comes to updating the prior with F-type stars, which we don't
currently have a lot of.

It's just curious that for a star at ~100muHz, the prior shouldn't allow
that range of epsilon at all. Also d02 should be 0.5muHz-1.25muHz or
similar. That looks more like 0.25.

Did you run the fit with the sampler='cpnest'? That might be a quickfix for
the issue.

**Comment by nielsenmb** [comment]
Currently working on this in dev branch.

This should be solved (along with issue #271) with the update to dimensionality reduction.
