### ISSUE TITLE
Can't run pbjam after installtion

### ISSUE THREAD

**Issue by diyiliaoya** [grd349/PBjam#269]
Hi all,

I am new user in PBjam. When I run PBjam as in the doc [https://pbjam.readthedocs.io/en/latest/example-session.html](url) , it didn't work. 
When I run `sess = pb.session(ID='KIC4448777',numax=(220.0, 3.0),dnu=(16.97, 0.05),teff=(4750, 250),bp_rp=(1.34, 0.1),exptime=1800,path = '.')` , 
the error is:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: session.__init__() got an unexpected keyword argument 'exptime'`

So I remove the "exptime", but it still didn't work:
Querying MAST for KIC4448777
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:159: LightkurveDeprecationWarning: The search_lightcurvefile function is deprecated and may be removed in a future version.
        Use search_lightcurve() instead.
  search_results = lk.search_lightcurvefile(target=id, **lkwargs)
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:368: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = _clean_lc(lc_col[0].PDCSAP_FLUX)
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))
/home/liaoya/anaconda3/envs/pbjam-env/lib/python3.10/site-packages/pbjam/session.py:370: LightkurveDeprecationWarning: The PDCSAP_FLUX function is deprecated and may be removed in a future version.
  lc0 = lc0.append(_clean_lc(lc.PDCSAP_FLUX))

**Comment by nielsenmb** [comment]
Hi diyiliaoya,

Are you using the pip installed version of PBjam? or the one this repo? 

We've had issues with keeping the Lightkurve part of PBjam up to date with their latest versions. The GitHub version of PBjam should work with the latest version of Lightkurve.

**Comment by diyiliaoya** [comment]
Yes, I used pip to install it. It's PBjam v1.0.0.
I'll try this repo. Thank you!

**Comment by diyiliaoya** [comment]
> Hi diyiliaoya,
> 
> Are you using the pip installed version of PBjam? or the one this repo?
> 
> We've had issues with keeping the Lightkurve part of PBjam up to date with their latest versions. The GitHub version of PBjam should work with the latest version of Lightkurve.

Hi nielsenmb,
Thank you for you reply. It worked instead of using this repo.
But it still has some warning. When I import pbjam, is shows this warning:
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions
Does it matter?

**Comment by nielsenmb** [comment]
No that shouldn't matter. It's a warning that PyMC3 shows when some helper packages aren't installed that make the Theano-based parts run faster. 

I've never had an issue with it being particularly slow though, so I admit I've never looked into it. 

Let me know how it goes!

**Comment by diyiliaoya** [comment]
Hi nielsenmb,

I have another question. Both in session and star class, there are two arguments called teff and bp_rp. 
How do I determine the values of these two arguments? I didn't find any docs about these.

**Comment by nielsenmb** [comment]
You'll need to look those up for the target you want. Usually what I do is
go to Simbad <http://simbad.u-strasbg.fr/simbad/sim-fid>and find the Gaia
entry for the target. There you can find the Teff and bp_rp that they've
measured.

If for some reason you can't get a reliable temperature, then using bp_rp
on its own should be fine. We included both in case either of the two
estimates was off, then the fit wouldn't be completely lost.

**Comment by diyiliaoya** [comment]
Thanks very much !

**Comment by diyiliaoya** [comment]
Hi nielsenmb

I got an dependency conflicts when I install the latest version.
The package statsmodels need numpy >=1.22.3, but pymc3 need numpy <1.22.2
So how should I do?
