### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by diyiliaoya** [grd349/PBjam#270]
Hi all

I got an dependency conflicts when I install the latest version.
The package statsmodels need numpy >=1.22.3, but pymc3 need numpy <1.22.2
So how should I do?

**Comment by nielsenmb** [comment]
Argh...that's annoying, another reason we need to get rid of some dependencies in PBjam...

I think the simplest way to go about it is using a virtual environment (for example with Python venv or Conda), and then install the packages you need for PBjam there. You can then manually install for example Statsmodels  v0.10, which probably doesn't require numpy 1.22.3, and then you can install numpy 1.22.2 instead.

**Comment by diyiliaoya** [comment]
Hi nielsenmb,

Thanks for your suggestion, I have installed PBjam in different machines.
Another question： In the PBjam docs, it says that PBjam can get individual ferquency. But I can't find it in which module. 
Can it get the data like in Table 1 in this paper: [https://iopscience.iop.org/article/10.3847/1538-4357/aadcf2](url)

**Comment by nielsenmb** [comment]
I recommend using the peakbag module for that. Depending on what you need them for, you can probably also use the asymptotic frequencies from the asy_peakbag module, but they are highly correlated. The peakbag module frequencies aren't though, so they are probably better.

If you follow the session class example on Readthedocs then it should run through the whole set of modules and produce a set of files with the mode frequencies at the end, from both asy_peakbag and peakbag.
