### ISSUE TITLE
Check memory consumption on large lists of targets

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#64]
EMCEE and matplotlib figure instances are possible sources of memory leaks. 

Check if this becomes an issue for large jobs ~100 tgts or more. 

A small leak may be tolerable.

**Comment by ojhall94** [comment]
So I recall from a previous project that, when running a bunch of MCMC stuff in a loop in a Jupyter Notebook, the memory isn't properly recycled until you exit the notebook. I'm not sure whether this is also the case if the MCMC code is done by a package written in .py though.

**Comment by nielsenmb** [comment]
Never use ipynb for big runs :)

It does get better when running emcee in a .py compared to ipynb, but emcee
still has some issues. Feel like we need to find someone who knows stuff
about memory handling in python.

**Comment by grd349** [comment]
DFM will be here tomorrow! 😁

**Comment by grd349** [comment]
I don't think we have seen any issues here - I'm closing until someone says there is a problem.
