### ISSUE TITLE
eschelle/ladder

### ISSUE THREAD

**Issue by nielsenmb** [grd349/PBjam#90]
Andrea asked if PBjam can make eschelle diagrams.

I told him it's something we can add.

Do you have a snippet for you ladder plots? The one with the subplots, and the spectrum divided into chunks. 

And if you have one for making the classic eschelles I can include that too. I think I have a function somewhere, but I'll need to dig it out.

**Comment by nielsenmb** [comment]
Labels for l=0 and l=2 should probably be added, so people know what they are looking at. 

Warrick suggested a potential enhancement. If the l=2  and l=0 ridges are split in two, the l=2 scale is not determined by the height of l=0, so they will be easier to see. 

Also, I would suggest having the option of plotting a traditional eschelle, and the ladder one. The ladder becomes difficult to use when you have many orders.

**Comment by grd349** [comment]
There is an echelle diagram in lightkurve - we should use this code by passing a periodogram object to the plot the echelle function, just as in epsilon.plot()

I will look at this ...

**Comment by nielsenmb** [comment]
Sounds good to me. Might need to make our own down the line, but it's good
for now.

**Comment by grd349** [comment]
All done and merged.
